#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : CopyQ
Version  : 3.12.0
Release  : 2
URL      : https://github.com/hluk/CopyQ/archive/v3.12.0/CopyQ-3.12.0.tar.gz
Source0  : https://github.com/hluk/CopyQ/archive/v3.12.0/CopyQ-3.12.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause GPL-3.0 LGPL-2.1
Requires: CopyQ-bin = %{version}-%{release}
Requires: CopyQ-data = %{version}-%{release}
Requires: CopyQ-lib = %{version}-%{release}
Requires: CopyQ-license = %{version}-%{release}
Requires: CopyQ-man = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : git
BuildRequires : libX11-dev libICE-dev libSM-dev libXau-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXft-dev libXi-dev libXinerama-dev libXi-dev libXmu-dev libXpm-dev libXrandr-dev libXrender-dev libXres-dev libXScrnSaver-dev libXt-dev libXtst-dev libXv-dev libXxf86misc-dev libXxf86vm-dev
BuildRequires : qtbase-dev
BuildRequires : qtbase-dev mesa-dev
BuildRequires : qtscript-dev
BuildRequires : qtsvg-dev
BuildRequires : qttools-dev
BuildRequires : qtx11extras-dev

%description
# CopyQ
[![Documentation Status](https://readthedocs.org/projects/copyq/badge/?version=latest)](https://copyq.readthedocs.io/en/latest/?badge=latest)
[![Translation Status](https://hosted.weblate.org/widgets/copyq/-/svg-badge.svg)](https://hosted.weblate.org/engage/copyq/?utm_source=widget)
[![Build Status](https://travis-ci.org/hluk/CopyQ.svg?branch=master)](https://travis-ci.org/hluk/CopyQ)
[![Windows Build Status](https://ci.appveyor.com/api/projects/status/github/hluk/copyq?branch=master&svg=true)](https://ci.appveyor.com/project/hluk/copyq)
[![Coverage Status](https://coveralls.io/repos/hluk/CopyQ/badge.svg?branch=master)](https://coveralls.io/r/hluk/CopyQ?branch=master)

%package bin
Summary: bin components for the CopyQ package.
Group: Binaries
Requires: CopyQ-data = %{version}-%{release}
Requires: CopyQ-license = %{version}-%{release}

%description bin
bin components for the CopyQ package.


%package data
Summary: data components for the CopyQ package.
Group: Data

%description data
data components for the CopyQ package.


%package lib
Summary: lib components for the CopyQ package.
Group: Libraries
Requires: CopyQ-data = %{version}-%{release}
Requires: CopyQ-license = %{version}-%{release}

%description lib
lib components for the CopyQ package.


%package license
Summary: license components for the CopyQ package.
Group: Default

%description license
license components for the CopyQ package.


%package man
Summary: man components for the CopyQ package.
Group: Default

%description man
man components for the CopyQ package.


%prep
%setup -q -n CopyQ-3.12.0
cd %{_builddir}/CopyQ-3.12.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1595346341
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1595346341
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/CopyQ
cp %{_builddir}/CopyQ-3.12.0/LICENSE %{buildroot}/usr/share/package-licenses/CopyQ/8624bcdae55baeef00cd11d5dfcfa60f68710a02
cp %{_builddir}/CopyQ-3.12.0/gpl.txt %{buildroot}/usr/share/package-licenses/CopyQ/8624bcdae55baeef00cd11d5dfcfa60f68710a02
cp %{_builddir}/CopyQ-3.12.0/plugins/itemfakevim/fakevim/LICENSE.LGPL %{buildroot}/usr/share/package-licenses/CopyQ/4df5d4b947cf4e63e675729dd3f168ba844483c7
cp %{_builddir}/CopyQ-3.12.0/qxt/COPYING %{buildroot}/usr/share/package-licenses/CopyQ/bc0979a68a9e0d11ae8d91b9d4fa8a5ea1889782
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/copyq

%files data
%defattr(-,root,root,-)
/usr/share/applications/com.github.hluk.copyq.desktop
/usr/share/copyq/themes/dark.ini
/usr/share/copyq/themes/forest.ini
/usr/share/copyq/themes/items.css
/usr/share/copyq/themes/light.ini
/usr/share/copyq/themes/main_window.css
/usr/share/copyq/themes/menu.css
/usr/share/copyq/themes/notification.css
/usr/share/copyq/themes/paper.ini
/usr/share/copyq/themes/scrollbar.css
/usr/share/copyq/themes/simple.ini
/usr/share/copyq/themes/solarized-dark.ini
/usr/share/copyq/themes/solarized-light.ini
/usr/share/copyq/themes/tooltip.css
/usr/share/copyq/themes/wine.ini
/usr/share/copyq/translations/copyq_ar.qm
/usr/share/copyq/translations/copyq_cs.qm
/usr/share/copyq/translations/copyq_da.qm
/usr/share/copyq/translations/copyq_de.qm
/usr/share/copyq/translations/copyq_es.qm
/usr/share/copyq/translations/copyq_fa.qm
/usr/share/copyq/translations/copyq_fr.qm
/usr/share/copyq/translations/copyq_hu.qm
/usr/share/copyq/translations/copyq_id.qm
/usr/share/copyq/translations/copyq_it.qm
/usr/share/copyq/translations/copyq_ja.qm
/usr/share/copyq/translations/copyq_ko.qm
/usr/share/copyq/translations/copyq_lt.qm
/usr/share/copyq/translations/copyq_nb.qm
/usr/share/copyq/translations/copyq_nl.qm
/usr/share/copyq/translations/copyq_pl.qm
/usr/share/copyq/translations/copyq_pt_BR.qm
/usr/share/copyq/translations/copyq_pt_PT.qm
/usr/share/copyq/translations/copyq_ru.qm
/usr/share/copyq/translations/copyq_sk.qm
/usr/share/copyq/translations/copyq_sv.qm
/usr/share/copyq/translations/copyq_tr.qm
/usr/share/copyq/translations/copyq_uk.qm
/usr/share/copyq/translations/copyq_zh_CN.qm
/usr/share/copyq/translations/copyq_zh_TW.qm
/usr/share/icons/hicolor/128x128/apps/copyq.png
/usr/share/icons/hicolor/16x16/apps/copyq.png
/usr/share/icons/hicolor/22x22/apps/copyq.png
/usr/share/icons/hicolor/24x24/apps/copyq.png
/usr/share/icons/hicolor/32x32/apps/copyq.png
/usr/share/icons/hicolor/48x48/apps/copyq.png
/usr/share/icons/hicolor/64x64/apps/copyq.png
/usr/share/icons/hicolor/scalable/apps/copyq.svg
/usr/share/icons/hicolor/scalable/apps/copyq_mask.svg
/usr/share/metainfo/com.github.hluk.copyq.appdata.xml

%files lib
%defattr(-,root,root,-)
/usr/lib/copyq/plugins/libitemencrypted.so
/usr/lib/copyq/plugins/libitemfakevim.so
/usr/lib/copyq/plugins/libitemimage.so
/usr/lib/copyq/plugins/libitemnotes.so
/usr/lib/copyq/plugins/libitempinned.so
/usr/lib/copyq/plugins/libitemsync.so
/usr/lib/copyq/plugins/libitemtags.so
/usr/lib/copyq/plugins/libitemtext.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/CopyQ/4df5d4b947cf4e63e675729dd3f168ba844483c7
/usr/share/package-licenses/CopyQ/8624bcdae55baeef00cd11d5dfcfa60f68710a02
/usr/share/package-licenses/CopyQ/bc0979a68a9e0d11ae8d91b9d4fa8a5ea1889782

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/copyq.1
